<?php
echo '

              <br>

                    <nav class="nav navbar navbar-default">
                        <p class="navbar-text pull-left">© 2017 - Hohner-Akkordeon-Orchester 1964 e. V. Reilingen
                        <a href="/Impressum.html" target="_blank" >Impressum</a>
                            <a href="Datenschutz.html" target="_blank">Datenschutz</a>
                    </p>
                        <!--a href="http://youtu.be/zJahlKPCL9g" class="navbar-btn btn-danger btn pull-right">
                            <span class="glyphicon glyphicon-star"></span>YouTube Kannal</a -->
                        <a href="https://www.facebook.com/HAO-Reilingen-126648524185021" class="navbar-btn btn-social-icon btn-facebook pull-right">
                            <span class="fa fa-facebook"></span>
                        </a>
                    </nav>
            </div>
        <div class="col-md-1"></div>
    </div>
</div>
<footer class="footer">
    <div class="container-fluid">
    </div>

</footer>
</body>
</html>
'; ?>
