<!DOCTYPE HTML >
<html>
<head lang="de">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
<?php

include_once 'lib.php';
if (isMobile()){
?>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="application/JavaScript" src="/static/js/jquery/jquery.min.js"></script>
    <script type="application/javascript" src="/static/js/bootstrap/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
<?php
}
else{
?>
    <script type="application/javascript" src="/static/js/jquery/jquery.js"></script>
    <script type="application/javascript" src="/static/js/bootstrap/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bootstrap-social.css">
    <link rel="stylesheet" href="/static/css/font-awesome.css">
    <link rel="shortcut icon" href="/static/images/icon.png" type="image/png">
<?php }
if (isset($INCS)){
	if(is_array($INCS)){
		foreach ($INCS as $ELEM){
			if(is_string($ELEM))
				echo "\t$ELEM\n";
		}
	}
	elseif (is_string($INCS))
		echo "\t$INCS\n";
}
?>
    <style type="text/css">
        body { background: white;background-image: url("/static/images/background.png");background-size:cover;}
        .navbar-brand{
            padding: 0 15px;
        }
    </style>
</head>
<body>
<div class="pageheader">
    <p></p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
            <div class="col-md-10">
