<?php
$Path = getcwd();
$FOLDER = dir("static/images/gallery");
$LOOPINDEX = 0;
?>
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-9">
        <div class="well">
<?php while ($ALBEN = $FOLDER->read()){
        	if ($ALBEN === "." || $ALBEN === "..") {
        		continue;
        	}
        	$VALUE = str_replace("_", " ", $ALBEN);
            if ($LOOPINDEX % 3 === 0)
            	echo "\t\t<div class=\"row\" style=\"margin:10px\">\n";
            ?>			<div class="col-md-4">         
                    <a href="/album.html?name=<?php echo $ALBEN; ?>"><img src="static/images/gallery/<?php echo $ALBEN; ?>/<?php 
                    $SHOW_PIC = dir("static/images/gallery/" . $ALBEN );
                    while($PICTURE= $SHOW_PIC->read()){
                    	if ($ALBEN === "." || $ALBEN === "..") {
                    		continue;
                    	}
                    	if (preg_match_all("/\.(jpe?g|GIF|png)/i", $PICTURE) > 0){
                    		echo $PICTURE;//."\">";
                    		break;
        				}
                    }?>" class="img-responsive"></a>
        			<h4><?php echo $VALUE;?></h4>
            </div>
<?php 
		
		$LOOPINDEX++;
		if($LOOPINDEX % 3 === 0){
			echo "\t\t</div>\n";
		}
        }
        if($LOOPINDEX % 3 !== 0){
        	echo "\t\t</div>\n";
        }
        ?>
        </div>
<?php $FOLDER->close();?>
    </div>
    
    <div class="col-md-2"></div>
</div>
