<br/>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">

        <div class="well"><!--  -->
            <h1>Unser Partner Vereine</h1>
            <h4>Wörner Cocktail</h4>
            <p><a href="http://www.woernercocktail.de/"><img src="/static/images/other/Woerner_logo.png"></a></p>
            <h4>Handharmonkia Vereinigung 1934 Rheingold Mannheim e.V.</h4>
            <p><a href="http://www.hhv-rheingold.de/index.php"><img src="/static/images/other/AiQ_final100-1.png"></a></p>
            <h4>Akkordeonverein Oedheim 1991 e.V</h4>
            <p><a href="http://www.akkordeonverein-oedheim.de/index.htm"><img src="/static/images/other/logo2016.gif" style="height:200px"></a></p>

        </div>
    </div>
    <div class="col-md-1"></div>
</div>