<?php 
?>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <div class="well">
            <h2>Jugendorchester</h2>
            <br>
            <div>
                <h4>Allgemines</h4>
                <br/>
                <img class="img-responsive img-rounded col-md-6" alt="Chania" src="/static/images/IMG_6215_downscaled.jpeg">
                <p>Hier sammeln unsere Jüngsten ab 10 Jahren nicht nur erste Erfahrungen im Orchesterspiel, sondern erleben die Freude an der Musik und am gemeinsamen Musizieren mit Freunden. Auch der Übergang ins 1. Orchester wird den Spielern durch den frühen Einstieg erleichtert.</p>
                <p>Im Programm befindet sich unter anderem die "New York Ouvertüre" von Kees Vlak mit dem das Orchester gemeinsam mit dem Jugendensemble unserer Freunde "Akkordeon im Quadrat" im Mai 2017 an den Deutschen  Meisterschaften für Jugendorchester teilgenonmen und den ersten Platz in der höchsten Kategorie erreicht haben. Herzlichen Glückwunsch an unsere deutschen Meister!!</p>
                <p>Aktuell arbeitet das Orchester an seinem Programm für das Jahreskonzert unserer Freunde aus Mannheim am 26.November.</p>
                <p>Geprobt wird jeden Mittwoch von <strong>18:30 Uhr</strong> bis <strong>20 Uhr</strong> in unserem Proberaum im Franz-Riegler-Haus Reilingen.</p>
            </div>
            <br>
            <div>
                <h4>Bundeswertungsspiele Düsseldorf</h4>
                <p>
                    Nach langer Vorbereitungszeit war es am 27.5 endlich soweit. Um 4:30 Uhr hieß es Abfahrt Richtung
                    Düsseldorf, denn schon um 10:15 Uhr sollte unser gemeinsamer Auftritt mit dem HHV Mannheim
                    stattfinden. Das fast 10 minütige Stück "New York Ouvertüre" sollte es in Höchstqualität geben.
                    Dementsprechend war die Aufregung groß. Das Stück begeisterte die Zuschauer und auch die Spieler
                    waren mit ihrer Darbietung hochzufrieden. Ob das auch die Jury so sah?<br/> Bis zur Siegerehrung um
                    18 Uhr galt es sich nun mit einem Besuch in der Düsseldorfer Innenstadt die Zeit zu vertreiben.
                    Dann war es so weit: die Bekanntgabe der Ergebnisse stand kurz bevor. Unsere Anspannung war zum
                    Greifen nah und stieg von Sekunde zu Sekunde. "Mittelstufe, Jugendorchester HWIE...." wir hörten
                    kaum noch hin. "Oberstufe, Akkordeon im Quadrat und Hohner AO Reilingen unter der Leitung von
                    Johannes Grebencikov in der Kategorie Orchester, Prädikat <b>Hervorragend</b> mit 43 Punkten! ". Die
                    Freude hierüber war groß und auf der anschießenden Busfahrt wurde ausgiebig gefeiert.
                </p>
            </div>

        </div>
    </div>
    <div class="col-md-2"></div>
</div>