<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well clearfix"><!-- well should have the clearfix  class for handling images -->
            <h3>1. Orchester</h3>
            <br/>
            <img alt="" style="height: 100%;" src="/static/images/IMG_6124_downscaled.jpeg" class="img-responsive col-md-6">
            <p></p>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>
