<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well clearfix"><!-- well should have the clearfix  class for handling images -->
            <h3>1. Orchester</h3>
            <br/>
            <img alt="" style="height: 100%;" src="/static/images/IMG_6124_downscaled.jpeg" class="img-responsive col-md-6">
            <h4 >Musik verbindet Generationen.  </h4>
			<p >So kommt es, dass die Sternchen des Vereins eine Altersspanne von knapp 50 Jahren überbrücken und dies mit Freude, Spaß und immer einem lockeren Spruch auf den Lippen. Wer sich in die Proben des 1. Orchesters gesellt, wird mit offenen Armen  junger und jung gebliebener hochmotivierter Spieler empfangen.</p>
			<p >Jeden Dienstag ab 20h drapieren sich über 20 Aktive um Dirigent Johannes Grebencikov und erarbeiten sowohl anspruchsvolle Originalkompositionen, als auch Ohrwürmer, die nicht zwangsläufig  weniger anspruchsvoll sind.  Trotz allem Ehrgeiz und Motivation, steht für alle der Spaß im Vordergrund.  So wird während der Proben zwar professionell gearbeitet, aber auch immer wieder herzlich gelacht.  Gute Stimmung zu verbreiten, gelingt der Mannschaft genauso zuverlässig,  wie punktgenau  das musikalische Können vor kritischen Jury Mitgliedern und einem breit gefächerten Publikum zu präsentieren. </p>
			<p >Die Erfolgreichen Konzerte,  sowie die Erlebnisse und Ergebnisse beim World Music Festival in Innsbruck sprechen für sich.</p>
			<p >Wie alle Orchester, ist auch das 1. Orchester des HAO regelmäßig bei Auftritten in der näheren Umgebung zu hören und zu sehen, doch auch in fernerer Umgebung war das Orchester bereits präsent. Im Jahre 2015 durfte die Truppe samt Familienmitgliedern bei einer unvergesslichen Konzertreise nach Rom, sein Können u.a. während einer Audienz von Papst Franziskus auf dem bis in die letzte Reihe gefüllten Petersplatz darbieten. </p>
			<p >Das 1. Orchester des HAO:  ein Orchester mit seinem ganz eigenen Charakter.</p>
			<p >Probezeit: Dienstags 20h, im Franz-Riegler Haus in Reilingen</p>
			<p >Dirigent: Johannes Grebencikov</p>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>
